"""High-level visualization views grouped by analysis domain."""

from .single_asset_profile.pricing.momentum_efficiency import (
    plot_candlestick_drawdown_recovery_view,
    plot_momentum_window_diagnostics_grid_view,
    plot_rolling_correlation_view,
    plot_seasonality_stack_view,
    plot_sharpe_surface_view,
    plot_sharpe_zscore_heatmap_view,
    plot_vix_fix_bands,
)
from .single_asset_profile.pricing.backtesting import plot_backtest_equity_curves_view
from .single_asset_profile.pricing.distribution import (
    plot_distribution_shape_zscores_view,
    plot_fixed_payout_strategy_backtest_view,
    plot_trade_range_breach_average_view,
    plot_trade_range_breach_excess_view,
    plot_trade_range_stack_view,
    plot_volatility_model_comparison_view,
)
from .single_asset_profile.pricing.factor_analysis import (
    plot_idiosyncratic_risk_view,
    plot_rolling_regression_view,
)
from .single_asset_profile.pricing.options_pricing import (
    plot_atm_iv_realized_view,
    plot_gbm_paths_view,
    plot_implied_volatility_by_strike_view,
    plot_iv_minus_realized_by_strike_view,
    plot_median_iv_minus_realized_view,
    plot_open_interest_overview_view,
    plot_open_interest_pot_ranges_view,
    plot_option_chain_table_view,
    plot_svi_surface_view,
)
from .single_asset_profile.pricing.predictive_modeling import (
    plot_forward_return_target_view,
    plot_prediction_probability_view,
)
from .single_asset_profile.valuation import (
    plot_analyst_price_target_band,
    plot_annual_vs_quarterly_dcf,
    plot_backfilled_dcf_vs_price,
    plot_balance_sheet_trends,
    plot_cash_conversion_capital_allocation,
    plot_cash_flow_trends,
    plot_dcf_snapshot_vs_price,
    plot_eps_dilution,
    plot_gross_margin_drivers,
    plot_income_statement_trends,
    plot_liquidity_capital_structure,
    plot_market_based_implied_pricing,
    plot_net_margin_drivers,
    plot_operating_margin_drivers,
    plot_price_target_premium_discount,
    plot_relative_value_vs_peer_medians,
    plot_revenue_segmentation,
    plot_seasonal_growth_rates,
    plot_ttm_profit_conversion,
)
from .portfolio_profile import (
    build_option_expiration_pl_figure,
    display_option_expiration_pl_view,
    format_snapshot_map,
    plot_benchmark_snapshot_zscores,
    plot_equity_curve,
    plot_options_expiration_ladder,
    plot_rolling_correlation as plot_portfolio_rolling_correlation,
    plot_rolling_portfolio_allocation,
    plot_rolling_portfolio_allocation_stacked,
    plot_rolling_sharpe_zscore,
    plot_rolling_sortino,
    plot_z_score_diff_dropdown,
)

__all__ = [
    "build_option_expiration_pl_figure",
    "display_option_expiration_pl_view",
    "format_snapshot_map",
    "plot_benchmark_snapshot_zscores",
    "plot_equity_curve",
    "plot_options_expiration_ladder",
    "plot_portfolio_rolling_correlation",
    "plot_rolling_portfolio_allocation",
    "plot_rolling_portfolio_allocation_stacked",
    "plot_rolling_sharpe_zscore",
    "plot_rolling_sortino",
    "plot_z_score_diff_dropdown",
    "plot_backtest_equity_curves_view",
    "plot_candlestick_drawdown_recovery_view",
    "plot_distribution_shape_zscores_view",
    "plot_idiosyncratic_risk_view",
    "plot_momentum_window_diagnostics_grid_view",
    "plot_rolling_correlation_view",
    "plot_seasonality_stack_view",
    "plot_sharpe_surface_view",
    "plot_sharpe_zscore_heatmap_view",
    "plot_atm_iv_realized_view",
    "plot_gbm_paths_view",
    "plot_implied_volatility_by_strike_view",
    "plot_iv_minus_realized_by_strike_view",
    "plot_median_iv_minus_realized_view",
    "plot_open_interest_overview_view",
    "plot_open_interest_pot_ranges_view",
    "plot_option_chain_table_view",
    "plot_svi_surface_view",
    "plot_forward_return_target_view",
    "plot_prediction_probability_view",
    "plot_rolling_regression_view",
    "plot_fixed_payout_strategy_backtest_view",
    "plot_trade_range_breach_average_view",
    "plot_trade_range_breach_excess_view",
    "plot_trade_range_stack_view",
    "plot_volatility_model_comparison_view",
    "plot_vix_fix_bands",
    "plot_analyst_price_target_band",
    "plot_annual_vs_quarterly_dcf",
    "plot_backfilled_dcf_vs_price",
    "plot_balance_sheet_trends",
    "plot_cash_conversion_capital_allocation",
    "plot_cash_flow_trends",
    "plot_dcf_snapshot_vs_price",
    "plot_eps_dilution",
    "plot_gross_margin_drivers",
    "plot_income_statement_trends",
    "plot_liquidity_capital_structure",
    "plot_market_based_implied_pricing",
    "plot_net_margin_drivers",
    "plot_operating_margin_drivers",
    "plot_price_target_premium_discount",
    "plot_relative_value_vs_peer_medians",
    "plot_revenue_segmentation",
    "plot_seasonal_growth_rates",
    "plot_ttm_profit_conversion",
]
